sudo: required
language: generic
services:
 - docker

before_install:
 - docker build -t githubbizzo/react-test -f ./client/Dockerfile-dev ./client

scripts:
 - docker run -e CI= true githubbizzo/react-test npm test

after_success:
 - docker build -t githubbizzo/complex-client ./client
 - docker build -t githubbizzo/complex-nginx ./nginx
 - docker build -t githubbizzo/complex-server ./server
 - docker build -t githubbizzo/complex-worker ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push githubbizzo/complex-client
 - docker push githubbizzo/complex-nginx
 - docker push githubbizzo/complex-server
 - docker push githubbizzo/complex-worker